### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by juliocezaroliveiragomes** [Dev-Force/express-conditional-tree-middleware#1]
Hi,

Is the library still in use? Is there any issue?

Whats the current status?

Regards

Julio

**Comment by Dev-Force** [comment]
Hi julio! To be honest, i havent used it since my thesis project but i am really comfortable to say that its working. be careful if you are going to use it in production though. Also care about the following line i am mentioning in readme file: 

> And Chainers are executed sequentially. OrChainers are using the Promise.any and as a result they are executed in parallel. I want to implement them soon. If anyone wants to contribute please go ahead :)
